services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false
